#!/bin/bash



function send_notification() {
	volume=$(awk "BEGIN {print $(wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -oE '[0-9]+(\.[0-9]+)?') *100}")

	is_speakers_muted=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep  "MUTED")
	TEXT=" Volume: $volume%"
	if [[ -n "$is_speakers_muted" ]]; then
		ICON="mute";
		TEXT=" Audio Muted"
		volume="0"
	elif [ "$volume" -lt 33 ]; then
		ICON="low";
	elif [ "$volume" -lt 66 ]; then
		ICON="medium";
	else
		ICON="high";
	fi

# 	if [[ -n "$is_speakers_muted" ]]; then
# 		notify-send -e -h string:synchronous:volume_notif -i "volume-mute" -t 2000 -r 9993 -u low " Audio Muted"
# 	else
		notify-send -e -h string:synchronous:volume_brightness_notif -h int:value:"$volume" -i "volume-$ICON" "$TEXT" -t 2000
# 	fi
}

case $1 in
up)
	# Set the volume on (if it was muted)
	wpctl set-mute @DEFAULT_AUDIO_SINK@ 0
	wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
	send_notification $1
	;;
down)
	wpctl set-mute @DEFAULT_AUDIO_SINK@ 0
	wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%-
	send_notification $1
	;;
mute-audio)
	wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
	send_notification $1
	;;
mute-mic)
	wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
	is_mic_muted=$(wpctl get-volume @DEFAULT_AUDIO_SOURCE@ | grep  "MUTED")

	if [[ -n "$is_mic_muted" ]]; then
		notify-send -e -h string:synchronous:mic_notif -i "mic-mute" -t 2000 -r 9993 -u low "Mic Muted"
	else
		notify-send -e -h string:synchronous:mic_notif -i "mic-unmute" -t 2000 -r 9993 -u low "Mic Unmuted"
	fi

esac


