#!/usr/bin/env bash


if pgrep -x "rofi" > /dev/null; then
  killall rofi
else
	divider="---------"

	notify-send "Getting list of available Wi-Fi networks..." -e -t 2000
	# Get a list of available wifi connections and morph it into a nice-looking list
	# wifi_list=$(<"$HOME/.config/rofi/scripts/wifi_list")
        wifi_list=$(nmcli --fields "SECURITY,SSID" device wifi list | sed 1d | sed 's/  */ /g' | sed -E "s/WPA*.?\S/ /g" | sed "s/^--/ /g" | sed "s/  //g" | sed "/--/d")
	connected=$(nmcli -fields WIFI g)
	if [[ "$connected" =~ "enabled" ]]; then
		toggle="󰖪  Disable Wi-Fi"
	elif [[ "$connected" =~ "disabled" ]]; then
		toggle="󰖩  Enable Wi-Fi"
	fi

	# Use rofi to select wifi network

	chosen_network=$(echo -e "x Close Window\n$toggle\n$divider\n$wifi_list" | uniq -u | rofi -dmenu -i 1 -p "Wi-Fi SSID: " -location 5 )
	# Get name of connection
	chosen_id="${chosen_network:2:-2}"

	if [ "$chosen_network" = "" ]; then
		exit
	elif [ "$chosen_network" = "󰖩  Enable Wi-Fi" ]; then
		nmcli radio wifi on
	elif [ "$chosen_network" = "󰖪  Disable Wi-Fi" ]; then
		nmcli radio wifi off
	else
		# Message to show when connection is activated successfully
		success_message="You are now connected to the Wi-Fi network \"$chosen_id\"."
		# Get saved connections
		saved_connections=$(nmcli -g NAME connection)
		if [[ $(echo "$saved_connections" | grep -w "$chosen_id") = "$chosen_id" ]]; then
			nmcli connection up id "$chosen_id" | grep "successfully" && notify-send "Connection Established" "$success_message" -i "wifi-check"  -e -t 2000
		else
			if [[ "$chosen_network" =~ "" ]]; then
				wifi_password=$(rofi -dmenu -password -p "Password: " -location 5 )
			fi
			nmcli device wifi connect "$chosen_id" password "$wifi_password" | grep "successfully" && notify-send "Connection Established" "$success_message"-i "wifi-check"  -e -t 2000
		fi
	fi
fi
